name: AG News Processing Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: agnews-processor:latest
          load: true

      - name: Create directories
        run: mkdir -p ztmp/data logs

      - name: Run unit tests
        run: |
         docker run --rm agnews-processor:latest python -m pytest /app/code/tests
            

      - name: Process specific words
        run: |
          docker run --rm \
            -v ./ztmp/data:/app/ztmp/data \
            -v ./logs:/app/logs \
            agnews-processor:latest \
            process_data \
            -cfg /app/code/config/cfg.yaml \
            -dataset news \
            -dirout "/app/ztmp/data/"

      - name: Process all words
        run: |
          docker run --rm \
            -v ./ztmp/data:/app/ztmp/data \
            -v ./logs:/app/logs \
            agnews-processor:latest \
            process_data_all \
            -cfg /app/code/config/cfg.yaml \
            -dataset news \
            -dirout "/app/ztmp/data/"

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: assignment-results
          path: |
            ztmp/data/*.parquet
            logs/
